### ISSUE TITLE
Cause: mvn.mob.com:80 failed to respond

### ISSUE THREAD

**Issue by Alvazz** [xiaojinzi123/IKnowAndroid#2]
下下来跑了一下，报这个错误

**Comment by xiaojinzi123** [comment]
跑是可以跑起来的, 用到了 mob 平台, mob 相关的下载不能走代理.

另外, 今天家里的服务器暂时停电了. 晚些才能恢复.

**Comment by Alvazz** [comment]
@xiaojinzi123 感谢及时回复，我已经先把mob部分去掉了，能跑起来，但是网络似乎拉不到数据:D:D

**Comment by xiaojinzi123** [comment]
> @xiaojinzi123 感谢及时回复，我已经先把mob部分去掉了，能跑起来，但是网络似乎拉不到数据:D:D

家里服务器暂时停电了, 你先去休闲一会, 晚点的时候家里会恢复电的.

**Comment by xiaojinzi123** [comment]
服务器已恢复....
